import { Button } from "std-widgets.slint";

import { DialogWindow } from "dialog.slint";
import { SetupView } from "setup.slint";
import { SettingsView } from "settings.slint";

export enum Page {
    Setup,
    Settings,
}

export component MainWindow inherits Window {
    preferred-width: 850px;
    preferred-height: 400px;
    min-width: 850px;
    min-height: 500px;

    property <Page> active_page: Page.Setup;
    in property <string> win_title;

    title: win_title;

    MenuBar {
        Menu {
            title: @tr("Vault");

            MenuItem {
                title: @tr("New Vault");
            }
            MenuItem {
                title: @tr("Open Vault");
            }
        }
        Menu {
            title: @tr("Items");

            MenuItem {
                title: @tr("New Item");
            }
            MenuItem {
                title: @tr("Edit Item");
            }
            MenuItem {
                title: @tr("Delete Item");
            }
        }
    }

    VerticalLayout {
        spacing: 10px;
        y: -20px;

        if active_page == Page.Setup : SetupView {}
        if active_page == Page.Settings : SettingsView {}

        // HorizontalLayout {
        //     spacing: 10px;

        //     Button {
        //         text: "Go to Setup";
        //         clicked => { active_page = Page.Setup }
        //     }

        //     Button {
        //         text: "Go to Settings";
        //         clicked => { active_page = Page.Settings }
        //     }
        // }
    }
}