import { Button, ListView } from "std-widgets.slint";

import { DialogWindow } from "dialog.slint";
import { SetupView } from "../views/setup.slint";
import { UnlockVaultView } from "../views/unlock_vault.slint";
import { VaultView } from "../views/vault.slint";

export enum Page {
    Setup,
    UnlockVault,
    Vault,
}

export component MainWindow inherits Window {
    preferred-width: 850px;
    preferred-height: 400px;
    min-width: 850px;
    min-height: 500px;

    callback open_create_database();
    callback open_unlock_vault();
    callback unlock_vault(string, string);
    
    in property <bool> disable_input: false;
    in property <string> win_title;
    in property <bool> vault_open: false;

    property <Page> active_page: Page.Setup;

    in-out property <string> vault_location: "";
    
    title: win_title;

    MenuBar {
        Menu {
            title: @tr("Vault");

            MenuItem {
                title: @tr("New Vault");
            }
            MenuItem {
                title: @tr("Open Vault");
            }
        }
        Menu {
            title: @tr("Items");

            MenuItem {
                title: @tr("New Item");
            }
            MenuItem {
                title: @tr("Edit Item");
            }
            MenuItem {
                title: @tr("Delete Item");
            }
        }
    }

    VerticalLayout {
        spacing: 10px;
        y: -20px;

        // Setup page
        if active_page == Page.Setup : SetupView {
            open_create_database => { open_create_database() }
            open_unlock_vault => { 
                open_unlock_vault();
                if vault_location != "" {
                    active_page = Page.UnlockVault;
                }
            }
        }

        // Unlock vault page
        if active_page == Page.UnlockVault : UnlockVaultView {
            vault_location: vault_location;
            unlock_clicked(location, password) => {
                unlock_vault(location, password);
                if vault_open {
                    active_page = Page.Vault;
                }
            }
            cancel_clicked => { vault_location = ""; active_page = Page.Setup; }
        }

        // Vault page
        if active_page == Page.Vault : VaultView {
            
        }
    }

    // We can use the TouchArea to cover the entires window to disable input when visible
    TouchArea {
        visible: disable_input;
        width: parent.width;
        height: parent.height;
        clicked => { /* swallow input */ }
    }
}