on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [published]

jobs:
  test:
    if: github.event_name != 'release'
    name: Run tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Cache Cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Install mold linker (Linux only)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y mold
          echo RUSTFLAGS=-C link-arg=-fuse-ld=mold >> $GITHUB_ENV
      - name: Run tests
        run: cargo test --verbose

  release:
    if: github.event_name == 'release'
    name: Build and publish release artifacts
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable
      - name: Install mold linker (Linux only)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y mold
          echo RUSTFLAGS=-C link-arg=-fuse-ld=mold >> $GITHUB_ENV
      - name: Build release binary
        run: cargo build --release --verbose
      - name: Upload to GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/NoPass
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
